//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trustev.Api.v1_1.Services.Transaction {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Tr" +
        "ansaction.Requests")]
    [System.SerializableAttribute()]
    public partial class AddTransactionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.SocialNetwork SocialNetworkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.TransactionData TransactionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.SocialNetwork SocialNetwork {
            get {
                return this.SocialNetworkField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialNetworkField, value) != true)) {
                    this.SocialNetworkField = value;
                    this.RaisePropertyChanged("SocialNetwork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.TransactionData TransactionData {
            get {
                return this.TransactionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDataField, value) != true)) {
                    this.TransactionDataField = value;
                    this.RaisePropertyChanged("TransactionData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNumberField, value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetwork", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.So" +
        "cial")]
    [System.SerializableAttribute()]
    public partial class SocialNetwork : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongTermAccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LongTermAccessTokenExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortTermAccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShortTermAccessTokenExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.ConstantsSocialNetworkType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongTermAccessToken {
            get {
                return this.LongTermAccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.LongTermAccessTokenField, value) != true)) {
                    this.LongTermAccessTokenField = value;
                    this.RaisePropertyChanged("LongTermAccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LongTermAccessTokenExpiry {
            get {
                return this.LongTermAccessTokenExpiryField;
            }
            set {
                if ((this.LongTermAccessTokenExpiryField.Equals(value) != true)) {
                    this.LongTermAccessTokenExpiryField = value;
                    this.RaisePropertyChanged("LongTermAccessTokenExpiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secret {
            get {
                return this.SecretField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretField, value) != true)) {
                    this.SecretField = value;
                    this.RaisePropertyChanged("Secret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortTermAccessToken {
            get {
                return this.ShortTermAccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortTermAccessTokenField, value) != true)) {
                    this.ShortTermAccessTokenField = value;
                    this.RaisePropertyChanged("ShortTermAccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShortTermAccessTokenExpiry {
            get {
                return this.ShortTermAccessTokenExpiryField;
            }
            set {
                if ((this.ShortTermAccessTokenExpiryField.Equals(value) != true)) {
                    this.ShortTermAccessTokenExpiryField = value;
                    this.RaisePropertyChanged("ShortTermAccessTokenExpiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.ConstantsSocialNetworkType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionData", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Tr" +
        "ansaction")]
    [System.SerializableAttribute()]
    public partial class TransactionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Trustev.Api.v1_1.Services.Transaction.Address> AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Trustev.Api.v1_1.Services.Transaction.TransactionItem> ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalBeforeTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalTaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Trustev.Api.v1_1.Services.Transaction.Address> Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Trustev.Api.v1_1.Services.Transaction.TransactionItem> Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBeforeTax {
            get {
                return this.TotalBeforeTaxField;
            }
            set {
                if ((this.TotalBeforeTaxField.Equals(value) != true)) {
                    this.TotalBeforeTaxField = value;
                    this.RaisePropertyChanged("TotalBeforeTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDelivery {
            get {
                return this.TotalDeliveryField;
            }
            set {
                if ((this.TotalDeliveryField.Equals(value) != true)) {
                    this.TotalDeliveryField = value;
                    this.RaisePropertyChanged("TotalDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDiscount {
            get {
                return this.TotalDiscountField;
            }
            set {
                if ((this.TotalDiscountField.Equals(value) != true)) {
                    this.TotalDiscountField = value;
                    this.RaisePropertyChanged("TotalDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTax {
            get {
                return this.TotalTaxField;
            }
            set {
                if ((this.TotalTaxField.Equals(value) != true)) {
                    this.TotalTaxField = value;
                    this.RaisePropertyChanged("TotalTax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Constants.SocialNetworkType", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types")]
    public enum ConstantsSocialNetworkType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Facebook = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Twitter = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LinkedIn = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trustev = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrustevSession = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Tr" +
        "ansaction")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryIsoA2CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.ConstantsAddressType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryIsoA2Code {
            get {
                return this.CountryIsoA2CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryIsoA2CodeField, value) != true)) {
                    this.CountryIsoA2CodeField = value;
                    this.RaisePropertyChanged("CountryIsoA2Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.ConstantsAddressType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionItem", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Tr" +
        "ansaction")]
    [System.SerializableAttribute()]
    public partial class TransactionItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalBeforeTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBeforeTax {
            get {
                return this.TotalBeforeTaxField;
            }
            set {
                if ((this.TotalBeforeTaxField.Equals(value) != true)) {
                    this.TotalBeforeTaxField = value;
                    this.RaisePropertyChanged("TotalBeforeTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDiscount {
            get {
                return this.TotalDiscountField;
            }
            set {
                if ((this.TotalDiscountField.Equals(value) != true)) {
                    this.TotalDiscountField = value;
                    this.RaisePropertyChanged("TotalDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTax {
            get {
                return this.TotalTaxField;
            }
            set {
                if ((this.TotalTaxField.Equals(value) != true)) {
                    this.TotalTaxField = value;
                    this.RaisePropertyChanged("TotalTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Constants.AddressType", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types")]
    public enum ConstantsAddressType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standard = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Billing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivery = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddTransactionStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Tr" +
        "ansaction.Requests")]
    [System.SerializableAttribute()]
    public partial class AddTransactionStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.ConstantsOrderStatusReason ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.ConstantsOrderStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.ConstantsOrderStatusReason Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((this.ReasonField.Equals(value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.ConstantsOrderStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Constants.OrderStatusReason", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types")]
    public enum ConstantsOrderStatusReason : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fraud = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complaint = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remorse = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Constants.OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types")]
    public enum ConstantsOrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Init = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Placed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refunded = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fulfilled = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refreshed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payment = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddTransactionBINRequest", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Tr" +
        "ansaction.Requests")]
    [System.SerializableAttribute()]
    public partial class AddTransactionBINRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BINNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BINNumber {
            get {
                return this.BINNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BINNumberField, value) != true)) {
                    this.BINNumberField = value;
                    this.RaisePropertyChanged("BINNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Ba" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trustev.Api.v1_1.Services.Transaction.GetTransactionResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTransactionResponse", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Tr" +
        "ansaction.Responses")]
    [System.SerializableAttribute()]
    public partial class GetTransactionResponse : Trustev.Api.v1_1.Services.Transaction.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Trustev.Api.v1_1.Services.Transaction.TransactionItem> ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.ConstantsOrderStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Timestamp1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalBeforeTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalTaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Trustev.Api.v1_1.Services.Transaction.TransactionItem> Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.ConstantsOrderStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Timestamp")]
        public System.DateTime Timestamp1 {
            get {
                return this.Timestamp1Field;
            }
            set {
                if ((this.Timestamp1Field.Equals(value) != true)) {
                    this.Timestamp1Field = value;
                    this.RaisePropertyChanged("Timestamp1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBeforeTax {
            get {
                return this.TotalBeforeTaxField;
            }
            set {
                if ((this.TotalBeforeTaxField.Equals(value) != true)) {
                    this.TotalBeforeTaxField = value;
                    this.RaisePropertyChanged("TotalBeforeTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDelivery {
            get {
                return this.TotalDeliveryField;
            }
            set {
                if ((this.TotalDeliveryField.Equals(value) != true)) {
                    this.TotalDeliveryField = value;
                    this.RaisePropertyChanged("TotalDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDiscount {
            get {
                return this.TotalDiscountField;
            }
            set {
                if ((this.TotalDiscountField.Equals(value) != true)) {
                    this.TotalDiscountField = value;
                    this.RaisePropertyChanged("TotalDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTax {
            get {
                return this.TotalTaxField;
            }
            set {
                if ((this.TotalTaxField.Equals(value) != true)) {
                    this.TotalTaxField = value;
                    this.RaisePropertyChanged("TotalTax");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/Social.Verify.Types.DataContracts.v1_1.Tr" +
        "ansaction.Requests")]
    [System.SerializableAttribute()]
    public partial class UpdateTransactionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.SocialNetwork SocialNetworkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trustev.Api.v1_1.Services.Transaction.TransactionData TransactionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.SocialNetwork SocialNetwork {
            get {
                return this.SocialNetworkField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialNetworkField, value) != true)) {
                    this.SocialNetworkField = value;
                    this.RaisePropertyChanged("SocialNetwork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trustev.Api.v1_1.Services.Transaction.TransactionData TransactionData {
            get {
                return this.TransactionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDataField, value) != true)) {
                    this.TransactionDataField = value;
                    this.RaisePropertyChanged("TransactionData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.trustev.com", ConfigurationName="v1_1.Services.Transaction.ITransactionService")]
    public interface ITransactionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.trustev.com/ITransactionService/AddTransaction", ReplyAction="https://api.trustev.com/ITransactionService/AddTransactionResponse")]
        void AddTransaction(Trustev.Api.v1_1.Services.Transaction.AddTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.trustev.com/ITransactionService/AddTransactionStatus", ReplyAction="https://api.trustev.com/ITransactionService/AddTransactionStatusResponse")]
        void AddTransactionStatus(Trustev.Api.v1_1.Services.Transaction.AddTransactionStatusRequest request, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.trustev.com/ITransactionService/AddTransactionBIN", ReplyAction="https://api.trustev.com/ITransactionService/AddTransactionBINResponse")]
        void AddTransactionBIN(Trustev.Api.v1_1.Services.Transaction.AddTransactionBINRequest request, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.trustev.com/ITransactionService/GetTransaction", ReplyAction="https://api.trustev.com/ITransactionService/GetTransactionResponse")]
        Trustev.Api.v1_1.Services.Transaction.GetTransactionResponse GetTransaction(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.trustev.com/ITransactionService/UpdateTransaction", ReplyAction="https://api.trustev.com/ITransactionService/UpdateTransactionResponse")]
        void UpdateTransaction(Trustev.Api.v1_1.Services.Transaction.UpdateTransactionRequest request, string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionServiceChannel : Trustev.Api.v1_1.Services.Transaction.ITransactionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionServiceClient : System.ServiceModel.ClientBase<Trustev.Api.v1_1.Services.Transaction.ITransactionService>, Trustev.Api.v1_1.Services.Transaction.ITransactionService {
        
        public TransactionServiceClient() {
        }
        
        public TransactionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddTransaction(Trustev.Api.v1_1.Services.Transaction.AddTransactionRequest request) {
            base.Channel.AddTransaction(request);
        }
        
        public void AddTransactionStatus(Trustev.Api.v1_1.Services.Transaction.AddTransactionStatusRequest request, string id) {
            base.Channel.AddTransactionStatus(request, id);
        }
        
        public void AddTransactionBIN(Trustev.Api.v1_1.Services.Transaction.AddTransactionBINRequest request, string id) {
            base.Channel.AddTransactionBIN(request, id);
        }
        
        public Trustev.Api.v1_1.Services.Transaction.GetTransactionResponse GetTransaction(string id) {
            return base.Channel.GetTransaction(id);
        }
        
        public void UpdateTransaction(Trustev.Api.v1_1.Services.Transaction.UpdateTransactionRequest request, string id) {
            base.Channel.UpdateTransaction(request, id);
        }
    }
}
